### PR TITLE
Fix for issue #2

### PR DESCRIPTION
**Pull request by fentie**
Reversed $payload_array assignment and unset calls. See Issue #2: https://github.com/xavierlacot/sfDoctrineRestGeneratorPlugin/issues/2

### CODE REVIEW

**Comment by xavierlacot** [comment]
This has been closed in #6. Thanks anyway for your contribution!

**Comment by fentie** [comment]
Just curious, is there something as far as etiquette/protocol that I did incorrectly here? The bug & pull request were exactly the same as the existing issue & pull request to fix.

**Comment by xavierlacot** [comment]
Nope, you didn't do anything in the wrong way. I just missed time during the last few weeks, and decided tonight to close a few opened issues... And just saw your contribution after the one that I merged before! Sorry if it might have bothered you :(

Cheers,

**Comment by fentie** [comment]
Understandable, that makes sense. I'm still relatively new to GitHub and just wanted to make sure I wasn't violating some unspoken rules.

Thanks for the plugin, it saved me quite a bit of time in my last project. 8^)

**Pull request closed without merging**
